### ISSUE TITLE
Move URL parsing to action creators

### ISSUE THREAD

**Issue by patrick-jones** [callum/redux-routing#2]
I am enjoying your minimal but effective library. However, I am having difficulty with this use case: I have a middleware that examines the authentication state and the current navigation path to decide if to send the user to a sign in page. It's based on [this example](https://github.com/Agamennon/react-redux-tiny/blob/master/src/shared/redux/middleware/appmiddleware.js) for a similar but neglected library.

The problem is that the URL isn't parsed until it passes through the middleware. This means that the content of the action differs based on the order that middlewares are added when creating the store.

I suggest moving the URL parsing bit from the middleware to the action creators so that the action payload is always in its final form. I also recommend exporting the constants.

I'd be glad to put together a pull request if you like.

**Comment by callum** [comment]
I've only just noticed this issue - I'm really sorry for the delay. Turns out I hadn't been watching my own repo.

Correct me if I'm wrong but my understanding is that middlewares cascade. Could you not always ensure that the routing middleware comes first, and have your redirection come next?

https://github.com/callum/redux-routing/blob/master/src/createMiddleware.js#L32-L37

You can see the the result of the routing middleware is passed as arguments to `next`, which in this case refers to the next middleware. So in theory, your redirection can be handled there. Here's an example:

```js
import { navigate } from 'redux-routing'

const authMiddleware = store => next => action => {
  // location is a parsed url
  const { location } = action

  if (!loggedIn && location.href !== '/login') {
    store.dispatch(navigate('/login'))
  }
}
```

Then it's just a case of composing your middlewares in the correct order:

```js
import { middleware as routingMiddleware } from 'redux-routing'
import { authMiddleware } from './authMiddleware'

const createStoreWithMiddleware =
  applyMiddleware(routingMiddleware, authMiddleware)(createStore)
const store = createStoreWithMiddleware(reducer)
```

Hope that helps.

**Comment by patrick-jones** [comment]
Yes, you are correct that it can be handled by changing the order of the middlewares.  However, the parsing work can just as easily be done in the action creators so that the action payload never changes through the life of the action. It is a friendlier, less surprising way that doesn't require any special treatment to play well with others.

**Comment by callum** [comment]
From what I can see there's not a very strong case for this. In this instance my preference is to keep the actions as simple as possible and have the middleware do the rest.

**Comment by plandem** [comment]
hmmm i tried this and have strange message about undefined 'href':
```
/**
 * Created by andrey on 26/01/16.
 */
import { applyMiddleware, createStore, compose } from 'redux'
import { createMiddleware, Hash, navigate, reducer, route } from 'redux-routing'
import { authMiddleware } from './authMiddleware'
import rootReducer from 'reducers/rootReducer'
import thunk from 'redux-thunk'

function withDevTools (middleware) {
	const devTools = window.devToolsExtension
		? window.devToolsExtension()
		: require('containers/DevTools').default.instrument();

	return compose(middleware, devTools);
}

export default function configureStore () {
	const routerMiddleware = createMiddleware(Hash);

	let middleware = [thunk, routerMiddleware, authMiddleware ];

	if (__DEBUG__) {
		var createLogger = require('redux-logger');
		middleware.push(createLogger());
	}

	middleware = applyMiddleware(...middleware);

	if(__DEBUG__) {
		middleware = withDevTools(middleware);
	}

	const store = middleware(createStore)(rootReducer);

	if (module.hot) {
		module.hot.accept('reducers/rootReducer', () => {
			const nextRootReducer = require('reducers/rootReducer').default;
			store.replaceReducer(nextRootReducer);
		})
	}

	return store;
}
```

and auth:
```
import { navigate } from 'redux-routing'

export const authMiddleware = store => next => action => {
	const { location } = action;
	const { currentUser } = store.getState();

	if (!currentUser && location.pathname !== '/login') {
		store.dispatch(navigate('/login'));
		return;
	}

	return next(action);
};
```

i'm getting error about history:
```
Cannot read property 'type' of undefined @ History.js?5edb:40
```
What do i miss?
