### ISSUE TITLE
Can you help with client-side only routing?

### ISSUE THREAD

**Issue by plandem** [callum/redux-routing#3]
Hello. Can you provide more 'client-side' only routing? How exactly to make routing? Looks like i did everything from example, but not working (only index path is showing):

```
import IndexView from 'views/IndexView/IndexView'
import FooView from 'views/FooView/FooView'
import FooListView from 'views/FooListView/FooListView'

const routes = [
	route('/', IndexView),
	route('/foo', FooListView),
	route('/foo/:bar', FooView)
];
```

and views like this:
```
import React from 'react'
import { navigate } from 'redux-routing'

export default class IndexView extends React.Component {
	render() {
		//this.props.dispatch(navigate('/foo'));
		return <div>IndexView <a href="/foo">Foo</a></div>
	}
}
```
```
import React from 'react'

export default class FooListView extends React.Component {
	render() {
		return <div>FooListView !!!!</div>
	}
}
```

and configure store like this:
```
export default function configureStore (initialState) {
	let middleware = applyMiddleware(thunk, createMiddleware(Hash));
	if (__DEBUG__) {
		var createLogger = require('redux-logger');
		middleware = applyMiddleware(createLogger());
	}

	const store = middleware(createStore)(rootReducer, initialState);
	return store;
}

```

**Comment by callum** [comment]
I can't tell exactly what's going on from your example, but it looks like the routing middleware is being overridden when `__DEBUG__` is truthy. Try this instead:

```js
import logger from 'redux-logger';

export default function configureStore (initialState) {
  const routingMiddleware = createMiddleware(Hash);
  let middleware = applyMiddleware(thunk, routingMiddleware);

  if (__DEBUG__) {
    middleware = applyMiddleware(logger(), thunk, routingMiddleware);
  }

  const store = middleware(createStore)(rootReducer, initialState);
  return store;
}
```

**Comment by plandem** [comment]
looks like yes. Am i right that to use 'hash' i have to hardcode all links with hash? like /#/foo? no any 'auto' normalize feature? And i can't understand how to use it with history instead of hash - links just does not work. It would be really helpful - one react example for pure react. I mean normal page with params and etc - not just 'links' and console. Because right know i also have to get route params at 'views' (handlers) too - was sure this feature is built-in.

**Comment by callum** [comment]
Please take a look at the example directory - it has exactly the example you're looking for. Using HTML5 History instead of hashes is as simple as switching `Hash` for `History` when you create the middleware. For a reference on how to create links, see: https://github.com/callum/redux-routing/blob/master/example/Handler.js

**Comment by plandem** [comment]
sorry, I missed about concept. Looks like it fit nice.
