### ISSUE TITLE
store not found with history

### ISSUE THREAD

**Issue by plandem** [callum/redux-routing#4]
I'm getting such kind of error when try to use 'back' button. Although 'back' works,  but meantime - error at console.

https://www.dropbox.com/s/0u3beyk0cljwyvw/Screenshot%202016-01-26%2002.20.17.png?dl=0

**Comment by callum** [comment]
Are you able to show me your application code?

**Comment by plandem** [comment]
looks like problem was here:
```
const createStoreWithMiddleware = applyMiddleware(compose(middleware, createLogger()))(createStore);
```

replaced with:
```
const createStoreWithMiddleware = applyMiddleware(middleware, createLogger())(createStore);
```

everything fine is now. I'm still missing when to use 'combine', when just pass array - in my head it's all same :(
