### ISSUE TITLE
constructUrl helper

### ISSUE THREAD

**Issue by plandem** [callum/redux-routing#6]
right now i have this helper:
```
const routes = {
	index: route('/', IndexView),
	documentList: route('/document', DocumentListView),
	documentView: route('/document/:id', DocumentView)
};

export const constructUrl = (url, options) => {
	let { matcher } = (routes.hasOwnProperty(url) ? routes[url] : { matcher: null});
	options = options || {};

	if(!matcher) {
		matcher = new Path(url);
	}

	if(matcher.hasUrlParams) {
		return matcher.params.reduce(function pathReducer(injected, key) {
			if(!options.hasOwnProperty(key)) {
				throw new Error('No value for param "' + key + '" of route: ' + injected);
			}

			return injected.replace(':'+key, encodeURIComponent(options[key]));
		}, matcher.path);
	}

	return matcher.path;
};

export default routes
```

later i can use it like:
```
class Link extends React.Component {
	constructor(props) {
		super(props);
		this.handleClick = this.handleClick.bind(this);
	}

	handleClick(e) {
		e.preventDefault();
		this.props.dispatch(navigate(e.target.href));
	}

	render() {
		const { onCLick, href, params, children, ...props} = this.props;
		let url = constructUrl(href, params);

		return (
			<a {...props} href={url} onClick={this.handleClick}>{children}</a>
		);
	}
}

Link.propTypes = {
	href: PropTypes.string,
	params: PropTypes.object,
	children: PropTypes.node.isRequired
};

export default connect()(Link);
```

and usage:
```
<Link href="documentList">Link to document list</Link>
```
or
```
<Link href="/document/:id" params={{id: 10}}>Link to view document</Link>
```
or
```
<Link href="documentView" params={{id: 10}}>Link to view document</Link>
```

i think it would be nice to have such kind of helper at your lib by default.

**Comment by callum** [comment]
Believe it or not, this functionality is already built in via the [path-parser](https://github.com/troch/path-parser) dependency. Every route you create has a [build method](https://github.com/callum/redux-routing/blob/master/src/route.js#L7) that you can construct a path with. This is often called 'reversing' a route.

```js
route('/:foo/:bar/:baz', handler).build({ foo: 1, bar: 2, baz: 2 }) // /1/2/3
```

Here's an example closer to what you're looking for (by no means tested...)

**routes.js**
```js
import { route } from 'redux-routing'
import Index from './Index'
import Document from './Document'

// define named routes
const routes = new Map()
routes.set('index', route('/', Index)
routes.set('document', route('/documents/:id', Document))

export default routes
```

**Link.js**
```js
import { navigate } from 'redux-routing'
import { routes } from './routes'

function Link (props) {
  const href = routes.get(props.route).build(props.params)

  return <a href={href} onClick={onClick}>{props.children}</a>

  function onClick (event) {
    props.dispatch(navigate(event.target.href))
    event.preventDefault()
  }
}

Link.propTypes = {
  route: PropTypes.string.isRequired,
  params: PropTypes.object
}

export default Link
```

**Usage**
```js
import Link from './Link'

<Link route="index">Index</Link>
// <a href="/">Index</a>
<Link route="document" params={{ id: 1 }}>Document 1</Link>
// <a href="/documents/1">Document 1</a>
```

**Comment by plandem** [comment]
ok, but built-in 'match' still not working with it because of:
```
for (const route of routes) {
		const matched = route.matcher.match(parsed.pathname);
}
```

because route in that case is array, afk.

**Comment by callum** [comment]
`routes.values()` :wink:

**Comment by plandem** [comment]
that's what i'm talking about - your 'match' does not work with Map actually :( i have to create own to solve this issue.

**Comment by callum** [comment]
Works just fine for me.

```
> const routing = require('redux-routing')
undefined
> const routes = new Map()
undefined
> routes.set('index', routing.route('/', 'index route'))
Map { [collapsed] }
> routes.set('document', routing.route('/document/:id', 'document route'))
Map { [collapsed] }
> routing.match('/document/34', routes.values())
{ handler: 'document route',
  params: { id: '34' },
  path: '/document/:id' }
```

**Comment by plandem** [comment]
looks like problem was at corrupted Root:
```
export default connect(route => ({ route }))(Root)
```

in my case it must be like this:
```
export default connect(state => ({ route: state.route }))(Root);
```


but! right now i have other problem - infinity loop in authMiddleware:
```
import { navigate } from 'redux-routing'

export const authMiddleware = store => next => action => {
	const { location } = action;
	const { currentUser } = store.getState();

	if (!currentUser && location.href !== '/login') {
		store.dispatch(navigate('/login'));
		return;
	}

	return next(action);
};
```

can you help me? I'm still newbie at redux/react and sometimes i'm stalling :(

p.s.: as i understand you don't use any flag like 'transiting' to make only 1 'event' same time. why?

**Comment by plandem** [comment]
sorry, looks like it was my fault:
```
import { navigate } from 'redux-routing'

export const authMiddleware = store => next => action => {
	if (!/^@@redux-routing/.test(action.type)) {
		return next(action)
	}

	const { currentUser } = store.getState();
	if(action.location.pathname !== '/login' && !currentUser) {
		return store.dispatch(navigate('/login'));
	}

	return next(action);
};
```

wrong logic about redirection.
BUT! i can't understand when sometimes there is 'location.href' and other time there is 'location.pathname' only. Why?

**Comment by plandem** [comment]
and btw, i still have problems with matching urls, as i said i have to use 'own' version of matching, because built-in is not working with Map. Here is my Root that is not working:
```
import React from 'react'
import { connect } from 'react-redux'
//import { match } from 'redux-routing'

import url from 'url'

function match (href, routes) {
	const parsed = url.parse(href);

	for (const route of routes.values()) {
		const matched = route.matcher.match(parsed.pathname);

		if (matched) {
			return {
				handler: route.handler,
				params: matched,
				path: route.path
			}
		}
	}
}

function Root(props) {
	const matched = match(props.route.href, props.routes);

	if (matched) {
		return <matched.handler {...props} />
	} else {
		return <div>404 not found</div>
	}
}

export default connect(state => ({ route: state.route }))(Root);
```

as you see there is a difference between iterating at your version of match and mine. If i'm trying to use built-in, then i get error about 'undefined'.

**Comment by callum** [comment]
The href isn't parsed until the action passes through the middleware: https://github.com/callum/redux-routing/blob/master/src/createMiddleware.js#L18-L24. To ensure the existence of pathname, just make sure that the routing middleware is added first, then it will be available to all middlewares that follow.

@plandem I really appreciate your interest in the project, but I'm afraid I don't have time to help with troubleshooting. It looks like the functionality you're looking for already exists, but I understand it can be a bit tricky to get it all working together.

If you encounter more problems, I really do urge you to take a look at the source code to understand how redux-routing works. It's purposefully very small.

Just to reiterate on the `Map` thing:

```js
import { route, match } from 'redux-routing'

const routes = new Map()
routes.set('foo', route('/foo', null))
routes.set('bar', route('/bar', null))

// only pass the map's values to the match function
const matched = match('/bar', routes.values())
```

**Comment by plandem** [comment]
yep, sorry. I'm sure it's because i'm still in process of learning what is react/redux is - only first attempt to create something with it. I just know that 'react-route' is monster to use for basic tasks and your solution fits ideally. 

p.s.: thanks, i didn't understand you about 'values', now i put it at the 'Root' and everything is ok.
