### ISSUE TITLE
modals?

### ISSUE THREAD

**Issue by plandem** [callum/redux-routing#7]
looks like 'modal' windows fit nice with such routing, but the only exception - i don't want to replace application root, i want to replace other root - root of modals. So right now i have to almost duplicate everything. I tried to create 'modalMiddleware' and put it before your middleWare to intercept 'modal links', but was  not success. So maybe some advice?  The main idea is:

root for common pages
```
<div id='root'/>
```

and root for modal pages
```
<div id='modal'/>
```

both will use same store and same routes. Actually i would like to use history too. So as i said, looks like your router can handle it, but i can't solve this task yet. So i will glad for any help.

**Comment by callum** [comment]
I'm afraid I don't really understand what you're asking. But it seems like it is beyond the scope of this project.
