### ISSUE TITLE
Example for work with hashes

### ISSUE THREAD

**Issue by pokidovea** [callum/redux-routing#8]
Hello! Please, give an example, how to work with urls, containing #hash. It seems to be  impossible, because matcher matches handlers only by pathname:
var matched = route.matcher.match(parsed.pathname);

**Comment by callum** [comment]
Hi @pokidovea - I seem to remember encountering the same problem a while ago. I had a brief look and this may be a limitation of https://github.com/troch/path-parser. It might be correct behaviour so I would check with the author of that library. To clarify I have tested with the following code:

```js
const Path = require('path-parser')
const path = new Path('foo/bar/:baz')
console.log(path.match('foo/bar/baz')) // -> {baz: "baz"}
console.log(path.match('foo/bar/baz#foo')) // -> null
```
